pipeline {
    environment {
       PATH = "$WORKSPACE/miniconda/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
    }
    stages {
        stage('setup miniconda') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                bash setup_miniconda.sh -p ${WORKSPACE}
                '''
            }
        }
        stage('build package') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                cd ${WORKSPACE}/my-first-blueprint-test
                source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                bash installer.sh -n my-first-blueprint-test
                conda activate my-first-blueprint-test
                pip install .
                '''
            }
        }
        stage('test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate my-first-blueprint-test
                cd ${WORKSPACE}/my-first-blueprint-test
                pytest tests
                '''
            }
        }
        stage('dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/my-first-blueprint-test
                bash installer.sh -n dev-my-first-blueprint-test -d
                conda activate dev-my-first-blueprint-test
                pip install --editable .
                '''
            }
        }
        stage('dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate dev-my-first-blueprint-test
                cd ${WORKSPACE}/my-first-blueprint-test
                pytest tests
                '''
            }
        }
        stage('pinned-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/my-first-blueprint-test
                bash installer.sh -n pinned-my-first-blueprint-test -p
                conda activate pinned-my-first-blueprint-test
                pip install .
                '''
            }
        }
        stage('pinned-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-my-first-blueprint-test
                cd ${WORKSPACE}/my-first-blueprint-test
                pytest tests
                '''
            }
        }
        stage('pinned-dev-environment') {
            steps {
                sh '''#!/usr/bin/env bash
                set -e
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda init bash
                conda activate
                cd ${WORKSPACE}/my-first-blueprint-test
                bash installer.sh -n pinned-dev-my-first-blueprint-test -p -d
                conda activate pinned-dev-my-first-blueprint-test
                pip install --editable .
                '''
            }
        }
        stage('pinned-dev-test') {
            steps {
                sh '''#!/usr/bin/env bash
                source $WORKSPACE/miniconda/etc/profile.d/conda.sh
                conda activate pinned-dev-my-first-blueprint-test
                cd ${WORKSPACE}/my-first-blueprint-test
                pytest tests
                '''
            }
        }
    }
}
